ALTER TABLE "Import" ADD COLUMN "currentStep" TEXT;
ALTER TABLE "Import" ADD COLUMN "progress" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Import" ADD COLUMN "lastErrorCode" TEXT;
ALTER TABLE "Import" ADD COLUMN "lastErrorMessage" TEXT;
ALTER TABLE "Import" ADD COLUMN "retryCount" INTEGER NOT NULL DEFAULT 0;
