ALTER TYPE "CategorizationStatus" ADD VALUE IF NOT EXISTS 'AUTO_APPLIED';
ALTER TYPE "CategorizationStatus" ADD VALUE IF NOT EXISTS 'REVIEW_LIGHT';

ALTER TABLE "Import" ADD COLUMN IF NOT EXISTS "lightReviewRows" INTEGER NOT NULL DEFAULT 0;
