export const qitusVendorMappingDefinitions = [
  ["ovh", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["aws", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["scaleway", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["google workspace", "LABEL_KEYWORD", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["notion", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["github", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["figma", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["canva", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["anthropic", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["openai", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["slack", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["sncf", "VENDOR_CONTAINS", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["uber", "VENDOR_CONTAINS", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["axa", "VENDOR_CONTAINS", "6161", "Assurances", 0, "EXEMPT"],
  ["assurance", "LABEL_KEYWORD", "6161", "Assurances", 0, "EXEMPT"],
  ["urssaf", "VENDOR_CONTAINS", "6451", "Cotisations URSSAF", 0, "OUT_OF_SCOPE"],
  ["amazon", "VENDOR_CONTAINS", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["apple", "VENDOR_CONTAINS", "2183", "Matériel de bureau et informatique", 0.2, "DOMESTIC_PURCHASE"],
  ["wetransfer", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["restaurant", "LABEL_KEYWORD", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["repas affaires", "LABEL_KEYWORD", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["qonto", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["frais bancaire", "LABEL_KEYWORD", "627", "Services bancaires", 0, "EXEMPT"],
  ["expert comptable", "LABEL_KEYWORD", "6226", "Honoraires", 0.2, "DOMESTIC_PURCHASE"],
  ["honoraires ec", "LABEL_KEYWORD", "6226", "Honoraires", 0.2, "DOMESTIC_PURCHASE"],
  ["remboursement cca", "LABEL_KEYWORD", "4551", "Associés - comptes courants", 0, "OUT_OF_SCOPE"],
  ["greffe", "LABEL_KEYWORD", "6227", "Frais d'actes et de contentieux", 0, "OUT_OF_SCOPE"],
  ["coworking", "LABEL_KEYWORD", "6132", "Locations immobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["mission conseil", "LABEL_KEYWORD", "706", "Prestations de services", 0.2, "DOMESTIC_SALE"],
  ["mission audit", "LABEL_KEYWORD", "706", "Prestations de services", 0.2, "DOMESTIC_SALE"],
  ["stripe payments", "VENDOR_CONTAINS", "511", "Valeurs à l'encaissement", 0, "OUT_OF_SCOPE"],
  ["payout", "LABEL_KEYWORD", "511", "Valeurs à l'encaissement", 0, "OUT_OF_SCOPE"],
  ["orange", "VENDOR_CONTAINS", "626", "Télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["sosh", "VENDOR_CONTAINS", "626", "Télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["free mobile", "VENDOR_CONTAINS", "626", "Télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["free telecom", "VENDOR_CONTAINS", "626", "Télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["sfr", "VENDOR_CONTAINS", "626", "Télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["red by sfr", "VENDOR_CONTAINS", "626", "Télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["bouygues telecom", "VENDOR_CONTAINS", "626", "Télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["bbox", "LABEL_KEYWORD", "626", "Télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["ovh telecom", "LABEL_KEYWORD", "626", "Télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["la poste mobile", "VENDOR_CONTAINS", "626", "Télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["bnp paribas", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["societe generale", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["société générale", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["credit agricole", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["crédit agricole", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["caisse d'epargne", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["caisse d’épargne", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["credit mutuel", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["crédit mutuel", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["banque populaire", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["boursobank", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["revolut", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["shine", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["cic", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["lcl", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["paypal", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["mangopay", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["sumup", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["izettle", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["swile", "VENDOR_CONTAINS", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["edenred", "VENDOR_CONTAINS", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["deliveroo", "VENDOR_CONTAINS", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["ubereats", "VENDOR_CONTAINS", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["uber eats", "VENDOR_CONTAINS", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["thefork", "VENDOR_CONTAINS", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["brasserie", "LABEL_KEYWORD", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["cafe", "LABEL_KEYWORD", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["café", "LABEL_KEYWORD", "6257", "Réceptions", 0.1, "DOMESTIC_PURCHASE"],
  ["hotel", "LABEL_KEYWORD", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["hôtel", "LABEL_KEYWORD", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["air france", "VENDOR_CONTAINS", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["transavia", "VENDOR_CONTAINS", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["easyjet", "VENDOR_CONTAINS", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["ryanair", "VENDOR_CONTAINS", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["ratp", "VENDOR_CONTAINS", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["tcl", "VENDOR_CONTAINS", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["navigo", "LABEL_KEYWORD", "6251", "Voyages et déplacements", 0.1, "DOMESTIC_PURCHASE"],
  ["totalenergies", "VENDOR_CONTAINS", "6061", "Fournitures non stockables", 0.2, "DOMESTIC_PURCHASE"],
  ["total energies", "VENDOR_CONTAINS", "6061", "Fournitures non stockables", 0.2, "DOMESTIC_PURCHASE"],
  ["edf", "VENDOR_CONTAINS", "6061", "Fournitures non stockables", 0.2, "DOMESTIC_PURCHASE"],
  ["engie", "VENDOR_CONTAINS", "6061", "Fournitures non stockables", 0.2, "DOMESTIC_PURCHASE"],
  ["eni", "VENDOR_CONTAINS", "6061", "Fournitures non stockables", 0.2, "DOMESTIC_PURCHASE"],
  ["ilek", "VENDOR_CONTAINS", "6061", "Fournitures non stockables", 0.2, "DOMESTIC_PURCHASE"],
  ["papeterie", "LABEL_KEYWORD", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["bureau vallee", "VENDOR_CONTAINS", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["bureau vallée", "VENDOR_CONTAINS", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["officedepot", "VENDOR_CONTAINS", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["office depot", "VENDOR_CONTAINS", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["carrefour", "VENDOR_CONTAINS", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["fnac", "VENDOR_CONTAINS", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["darty", "VENDOR_CONTAINS", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["ldlc", "VENDOR_CONTAINS", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["back market", "VENDOR_CONTAINS", "6064", "Fournitures administratives", 0.2, "DOMESTIC_PURCHASE"],
  ["la poste", "VENDOR_CONTAINS", "626", "Frais postaux et télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["colissimo", "LABEL_KEYWORD", "626", "Frais postaux et télécommunications", 0.2, "DOMESTIC_PURCHASE"],
  ["chronopost", "VENDOR_CONTAINS", "6241", "Transports sur achats", 0.2, "DOMESTIC_PURCHASE"],
  ["ups", "VENDOR_CONTAINS", "6241", "Transports sur achats", 0.2, "DOMESTIC_PURCHASE"],
  ["dhl", "VENDOR_CONTAINS", "6241", "Transports sur achats", 0.2, "DOMESTIC_PURCHASE"],
  ["dpd", "VENDOR_CONTAINS", "6241", "Transports sur achats", 0.2, "DOMESTIC_PURCHASE"],
  ["meta ads", "LABEL_KEYWORD", "623", "Publicité", 0.2, "DOMESTIC_PURCHASE"],
  ["facebook ads", "LABEL_KEYWORD", "623", "Publicité", 0.2, "DOMESTIC_PURCHASE"],
  ["google ads", "LABEL_KEYWORD", "623", "Publicité", 0.2, "DOMESTIC_PURCHASE"],
  ["linkedin ads", "LABEL_KEYWORD", "623", "Publicité", 0.2, "DOMESTIC_PURCHASE"],
  ["tiktok ads", "LABEL_KEYWORD", "623", "Publicité", 0.2, "DOMESTIC_PURCHASE"],
  ["mailchimp", "VENDOR_CONTAINS", "623", "Publicité", 0.2, "DOMESTIC_PURCHASE"],
  ["brevo", "VENDOR_CONTAINS", "623", "Publicité", 0.2, "DOMESTIC_PURCHASE"],
  ["typeform", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["zapier", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["make.com", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["airtable", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["microsoft", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["adobe", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["dropbox", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["calendly", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["zoom", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["loom", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["linear", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["vercel", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["render", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["clever cloud", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["heroku", "VENDOR_CONTAINS", "6135", "Locations mobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["stripe", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["malt", "VENDOR_CONTAINS", "627", "Services bancaires", 0, "EXEMPT"],
  ["legalstart", "VENDOR_CONTAINS", "6227", "Frais d'actes et de contentieux", 0.2, "DOMESTIC_PURCHASE"],
  ["captain contrat", "VENDOR_CONTAINS", "6227", "Frais d'actes et de contentieux", 0.2, "DOMESTIC_PURCHASE"],
  ["avocat", "LABEL_KEYWORD", "6226", "Honoraires", 0.2, "DOMESTIC_PURCHASE"],
  ["notaire", "LABEL_KEYWORD", "6227", "Frais d'actes et de contentieux", 0.2, "DOMESTIC_PURCHASE"],
  ["inpi", "VENDOR_CONTAINS", "6227", "Frais d'actes et de contentieux", 0, "OUT_OF_SCOPE"],
  ["infogreffe", "VENDOR_CONTAINS", "6227", "Frais d'actes et de contentieux", 0, "OUT_OF_SCOPE"],
  ["dougs", "VENDOR_CONTAINS", "6226", "Honoraires", 0.2, "DOMESTIC_PURCHASE"],
  ["indy", "VENDOR_CONTAINS", "6226", "Honoraires", 0.2, "DOMESTIC_PURCHASE"],
  ["tiime", "VENDOR_CONTAINS", "6226", "Honoraires", 0.2, "DOMESTIC_PURCHASE"],
  ["dext", "VENDOR_CONTAINS", "6226", "Honoraires", 0.2, "DOMESTIC_PURCHASE"],
  ["impot gouv", "LABEL_KEYWORD", "635", "Autres impôts, taxes et versements assimilés", 0, "OUT_OF_SCOPE"],
  ["impôts gouv", "LABEL_KEYWORD", "635", "Autres impôts, taxes et versements assimilés", 0, "OUT_OF_SCOPE"],
  ["dgfip", "VENDOR_CONTAINS", "635", "Autres impôts, taxes et versements assimilés", 0, "OUT_OF_SCOPE"],
  ["sie", "VENDOR_CONTAINS", "635", "Autres impôts, taxes et versements assimilés", 0, "OUT_OF_SCOPE"],
  ["cfe", "LABEL_KEYWORD", "635", "Autres impôts, taxes et versements assimilés", 0, "OUT_OF_SCOPE"],
  ["taxe fonciere", "LABEL_KEYWORD", "635", "Autres impôts, taxes et versements assimilés", 0, "OUT_OF_SCOPE"],
  ["taxe foncière", "LABEL_KEYWORD", "635", "Autres impôts, taxes et versements assimilés", 0, "OUT_OF_SCOPE"],
  ["malakoff humanis", "VENDOR_CONTAINS", "645", "Charges de sécurité sociale et de prévoyance", 0, "OUT_OF_SCOPE"],
  ["alan", "VENDOR_CONTAINS", "645", "Charges de sécurité sociale et de prévoyance", 0, "OUT_OF_SCOPE"],
  ["ag2r", "VENDOR_CONTAINS", "645", "Charges de sécurité sociale et de prévoyance", 0, "OUT_OF_SCOPE"],
  ["harmonie mutuelle", "VENDOR_CONTAINS", "645", "Charges de sécurité sociale et de prévoyance", 0, "OUT_OF_SCOPE"],
  ["wework", "VENDOR_CONTAINS", "6132", "Locations immobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["morning", "VENDOR_CONTAINS", "6132", "Locations immobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["wojo", "VENDOR_CONTAINS", "6132", "Locations immobilières", 0.2, "DOMESTIC_PURCHASE"],
  ["deskeo", "VENDOR_CONTAINS", "6132", "Locations immobilières", 0.2, "DOMESTIC_PURCHASE"],
] as const;
